export const CONSTANT = {
  "SUCCESS": "SUCCESS",
  "INTERCEPTOR_TIMEOUT": 3000,
  "EXCL_SUFFIX": ["XLSX"],
  "PRODUCT_NAME": "",
  "DIALOG_TITLE": "系统提示",
  "DIALOG_DEFAULT_WIDTH": "350px",
  "DIALOG_DEFAULT_HEIGHT": "400px",
  "LOGIN_USERNAME_NULL_MESSAGE": "用户名不能为空",
  "LOGIN_PASSWORD_NULL_MESSAGE": "密码不能为空",
  "LOGIN_ERROR_MESSAGE": "用户名或密码错误",
  "ERROR_MESSAGE": "服务器异常,请稍候再试!",
  "TOKEN_EXPIRED_ERROR": "登陆超时,请重新登陆!",
  "LOGOUT_ERROR_MESSAGE": "登出异常",
  "LOGOUT_SUCCESS_MESSAGE": "登出成功",
  "CANCEL_BUTTON_TEXT": "取消",
  "OK_BUTTON_TEXT": "确定",
  "LOADING": "数据加载中, 请稍候",
  "PIC_SUFFIX": "image/jpg,image/png,image/jpeg,image/gif",
  "EXCEL_SUFFIX": "application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "LOGIN_URL": "/login",
  "MAIN_URL": "/home",
  "LINK": "/info",
  "USER_OPTION_SETTING_KEY": "sBf0cnonz931-79vC0Ho434d-b4Sa46vk46LmY",
  "USER_PAGE_SETTING_KEY": "pf8589d-fa67tAK76-21h4C#98-h7Epa"
}

export const SYSTEM_UTIL = {
  "PROJECT_PATH": "/workflow",
  "INDEX_URL": "/",
  "AUTH_TOKEN": "2E1CD-C19F-3E85-F6F1-E92028EF8",
  "LOCAL_TOKEN": "LITb8KJNV6Xba10arAuPf6Gm^Q9Ct6X6",
  "AUTH_USERNAME_TOKEN": "t4JycOU9OmvCS6XoFC95T6FxTE02sJqO",
  "AUTH_SECRET_PREFIX": "MU2FSD_QGV_KX1/BDP9PKT+G5_Y7Y6NK_BTL2HBB_SXJ5C8F",
  "AUTH_SECRET_SUFFIX": "OE1kDI8F100sp1AkywAZIzWx",
  "TOKEN_EXPIRED_CODE": "5000",
  "TOKEN_ILLEGAL_CODE": "DEV_ZUUL_500100",
  "DEFAULT_EXCEL_NAME": "报表",
  "DEFAULT_EXCEL_SUFFIX": ".xlsx",
  "TREE_ROOT_NAME": "KJ0982DJFAcme3ufd214d0JDJJDHvqdjKHES",
  "TOKEN": "LITb8KJNV6Xba10arAuPf6Gm^Q9Ct6X6"
}

export const REQUEST = {
  "METHOD_POST": "POST",
  "METHOD_GET": "GET",
  "METHOD_PUT": "PUT",
  "METHOD_DELETE": "delete",
  "FORM": "FORM",
  "FALSE": "false",
  "TRUE": "true",
  "CONTENT_TYPE_NAME": "Content-Type",
  "CONTENT_LENGTH_NAME": "content-length",
  "DEFAULT_URL_FORMAT": "JSON",
  "DEFAULT_CONTENT_TYPE": "application/json;charset=UTF-8",
  "DEFAULT_FORM_URLENCODED": "application/x-www-form-urlencoded;charset=UTF-8",
  "X_REQUESTED_WITH": "x-requested-with",
  "DEFAULT_X_REQUESTED_WITH": "XMLHttpRequest",
  "URL_TOKEN": SYSTEM_UTIL.AUTH_TOKEN,
  "X_REFRESH": "x-refresh",
  "UNDERLINE": "_",
  "OBSERVE": "response",
  "BLOB": "blob",
  "EXCEL": "EXCEL",
  "DOWNLOAD": "DOWNLOAD",
  "TEXT_PLAIN": "text/plain",
  "EXCEL_TYPE": "application/msexcel",
  "STATUS": "status",
  "ERROR": "error",
  "CODE": "code",
  "SUCCESS": "success",
  "RESULT": "result",
  "REASON": "reason",
  "ERROR_REASON": "errorReason",
  "SUCCESS_CODE": 200,
  "EXCEL_HEADER_CONTENT_DISPOSITION": "content-disposition",
  "FILENAME": "FILENAME"
}
